### ISSUE TITLE
Evaluation of limitPriceX96 while Long execution.

### ISSUE THREAD

**Issue by debo24** [eq-lab/marginly#176]
While performing long execute, the long function accepts parameter limitPriceX96, how this has been calculated in the main application? I tried performing the simple calculation as mentioned here but it does not match with the calculation on the given transaction.
Txn: https://arbiscan.io/tx/0xe6c8268863e6a2e23229ddf55789f44c06c52535b5dcc81326ddca78c033008b

Here is the calculation that I took reference from,
https://docs.uniswap.org/contracts/v4/concepts/managing-positions

Please clear with me about the calculation of limitPriceX96 in long execution or short as well, as the calculation mentioned by the uniswap documentation does not match with the results passed in the transaction, mentioned in txn link.

**Comment by alex-nax** [comment]
Hi, @debo24 in our ui we define slipage
`const SLIPPAGE = 0.05;`

**Comment by optifat** [comment]
Closing since no further questions followed
